name: Sync code and create PR to Secondary Repo

on:
  push:
    branches:
      - main

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest

    env:
      TARGET_REPO: TVSM-Common-Support/tvsm-sync-repo-copy
      TARGET_BRANCH: main

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4


      - name: Set up Git with real commit user
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"

      - name: Create unique branch name
        id: branch
        run: | 
          echo "branch=sync-$(date +%s)" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
          echo "${{ steps.branch.outputs.branch }}"

      - name: Add secondary repo as remote and push
        run: |
          git remote add target "https://${{ secrets.USERNAME }}:${{ secrets.TARGET_REPO_PAT }}@github.com/${{ env.TARGET_REPO }}.git"
          git checkout -b ${{ steps.branch.outputs.branch }}
          git push --set-upstream target ${{ steps.branch.outputs.branch }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TARGET_REPO_PAT }}
          repository: ${{ env.TARGET_REPO }}
          title: "Auto-sync from primary repo"
          head: ${{ steps.branch.outputs.branch }}
          base: ${{ env.TARGET_BRANCH }}
          body: |
            This PR was automatically created by GitHub Actions to sync code from the primary repository.
